name: vim

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        version:
          - nightly
          - v8.2.0235
          - v8.1.2424
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: false
          version: ${{ matrix.version }}
      - name: Download test runner
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Prepare environment
        run: |
          git config --global user.name "github-action"
          git config --global user.email "github-action@example.com"
      - name: Run tests
        env:
          CI: 1
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis
